version: '3'
services:
#DB--------------------------------
  service-database:
    container_name: dely-database
    image: mdillon/postgis:11-alpine
    environment: 
      - POSTGRES_DB=dely
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
     - "5555:5432"
    volumes: 
     - /c/Program Files/PostgreSQL/11/data
